require('megachel.packer')
require('megachel.themeRosePine')
require('megachel.drevo')
require('megachel.highlight')
require('megachel.remap')
require('megachel.set')
-- require('megachel.themeNeoSolarized')
require('megachel.comment')
require('megachel.indentation-lines')
require('megachel.LSP')
