require("megachel.packer")
-- require("megachel.theme-kanagawa")
require("megachel.theme-catppuccin")
require("megachel.feline")
-- require("megachel.themeRosePine")
require("megachel.drevo")
-- require("megachel.npm-info")
require("megachel.highlight")
require("megachel.remap")
require("megachel.set")
-- require('megachel.themeNeoSolarized')
require("megachel.comment")
require("megachel.indentation-lines")
require("megachel.LSP")
require("megachel.linter")
require("megachel.conform")
require("megachel.aerial")
